name: CI

on:
  push:
    branches:
      - main
      - 'feat/**'
      - 'release/**'
#      TODO: Remove this once we have a stable release branch
      - 'task/**'
  pull_request:
    branches:
      - main
      - 'feat/**'
      - 'release/**'
#      TODO: Remove this once we have a stable release branch
      - 'task/**'

jobs:
  setup:
    name: Detect Changed Packages
    runs-on: ubuntu-latest
    outputs:
      changed_apps: ${{ steps.set-matrix.outputs.changed_apps }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Determine base ref
        id: base
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "base_ref=${{ github.base_ref }}" >> $GITHUB_OUTPUT
          else
          # Fallback if origin/main doesn't exist
          echo "base_ref=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_OUTPUT
          fi

      - name: Get changed apps
        id: set-matrix
        run: |
          BASE=$(git merge-base ${{ steps.base.outputs.base_ref }} HEAD || git rev-list --max-parents=0 HEAD)
          echo "Using base commit: $BASE"

          pnpm exec lerna list --since $BASE --json | jq -r '.[] | select(.location | test("apps/")) | .name' > changed.txt
          cat changed.txt

          APPS=$(jq -R -s -c 'split("\n") | map(select(length > 0)) | map({app: .})' changed.txt)
          echo "changed_apps=${APPS}" >> $GITHUB_OUTPUT
  build:
    needs: setup
    if: needs.setup.outputs.changed_apps != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.setup.outputs.changed_apps) }}

    name: Build and Test - ${{ matrix.app }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: debug
        run: |
          echo "Changed app: ${{ matrix.app }}"
          echo "Current working directory: $(pwd)"
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "PNPM version: $(pnpm -v)"
          echo "Branch: ${{ github.head_ref || github.ref }}"

      - name: Lint ${{ matrix.app }}
        run: pnpm exec lerna run lint --scope ${{ matrix.app }}

      - name: Type Check ${{ matrix.app }}
        run: pnpm exec lerna run typecheck --scope ${{ matrix.app }}

      - name: Test ${{ matrix.app }}
        run: pnpm exec lerna run test:ci --scope ${{ matrix.app }}

      - name: Build ${{ matrix.app }}
        run: pnpm exec lerna run build --scope ${{ matrix.app }}
