name: CI

on:
  push:
    branches:
      - main
      - 'feat/**'
      - 'release/**'
      - 'task/**' # TODO: remove once stable
  pull_request:
    branches:
      - main
      - 'feat/**'
      - 'release/**'
      - 'task/**'

jobs:
  setup:
    name: Detect Changed Packages
    runs-on: ubuntu-latest
    outputs:
      changed_apps: ${{ steps.set-matrix.outputs.changed_apps }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for git diff

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Determine base ref
        id: base
        run: .github/scripts/determine_base_ref.sh

      - name: Get changed apps
        id: set-matrix
        run: .github/scripts/get_changed_apps.sh ${{ steps.base.outputs.base_ref }}

      - name: Summary
        run: |
          echo "Changed apps: ${{ steps.set-matrix.outputs.changed_apps }}"

  build:
    needs: setup
    if: needs.setup.outputs.changed_apps != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.setup.outputs.changed_apps) }}

    name: Build & Test - ${{ matrix.app }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # faster

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Restore pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies (from cache)
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm exec lerna run lint --scope ${{ matrix.app }}

      - name: Type Check
        run: pnpm exec lerna run typecheck --scope ${{ matrix.app }}

      - name: Test
        run: pnpm exec lerna run test:ci --scope ${{ matrix.app }}

      - name: Build
        run: pnpm exec lerna run build --scope ${{ matrix.app }}
