name: CI

on:
  push:
    branches:
      - main
      - 'feat/**'
      - 'release/**'
#      TODO: Remove this once we have a stable release branch
      - 'task/**'
  pull_request:
    branches:
      - main
      - 'feat/**'
      - 'release/**'
#      TODO: Remove this once we have a stable release branch
      - 'task/**'

jobs:
  setup:
    name: Detect Changed Packages
    runs-on: ubuntu-latest
    outputs:
      changed_apps: ${{ steps.set-matrix.outputs.changed_apps }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for diffing

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Determine the base commit for diffing
      - name: Determine base ref
        id: base
        run: |
          set -euo pipefail
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "base_ref=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
          elif [ -n "${{ github.event.before }}" ] && [ "${{ github.event.before }}" != "0000000000000000000000000000000000000000" ]; then
            echo "base_ref=${{ github.event.before }}" >> $GITHUB_OUTPUT
          else
            git fetch origin main || true
            if git rev-parse origin/main >/dev/null 2>&1; then
              echo "base_ref=$(git rev-parse origin/main)" >> $GITHUB_OUTPUT
            else
              echo "base_ref=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_OUTPUT
            fi
          fi

      # Find changed apps using lerna and jq
      - name: Get changed apps
        id: set-matrix
        run: |
          set -euo pipefail
          BASE=${{ steps.base.outputs.base_ref }}
          echo "Using base commit: $BASE"
          pnpm exec lerna list --since $BASE --json | jq -r '.[] | select(.location | test("apps/")) | .name' > changed.txt
          cat changed.txt
          if [ -s changed.txt ]; then
            APPS=$(jq -R -s -c 'split("\n") | map(select(length > 0)) | map({app: .})' changed.txt)
          else
            APPS="[]"
          fi
          echo "changed_apps=${APPS}" >> $GITHUB_OUTPUT

      # Output a summary for debugging
      - name: Summary of changed apps
        run: |
          echo "Changed apps matrix: ${{ steps.set-matrix.outputs.changed_apps }}"

      # Fail early if no changed apps detected (optional, comment out if you want to allow empty builds)
      - name: Validate changed apps
        if: steps.set-matrix.outputs.changed_apps == '[]'
        run: |
          echo "No changed apps detected. Exiting."
          exit 1

  build:
    needs: setup
    if: needs.setup.outputs.changed_apps != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.setup.outputs.changed_apps) }}

    name: Build and Test - ${{ matrix.app }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for diffing

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: debug
        run: |
          echo "Changed app: ${{ matrix.app }}"
          echo "Current working directory: $(pwd)"
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "PNPM version: $(pnpm -v)"
          echo "Branch: ${{ github.head_ref || github.ref }}"

      - name: Lint ${{ matrix.app }}
        run: pnpm exec lerna run lint --scope ${{ matrix.app }}

      - name: Type Check ${{ matrix.app }}
        run: pnpm exec lerna run typecheck --scope ${{ matrix.app }}

      - name: Test ${{ matrix.app }}
        run: pnpm exec lerna run test:ci --scope ${{ matrix.app }}

      - name: Build ${{ matrix.app }}
        run: pnpm exec lerna run build --scope ${{ matrix.app }}
